[project]
name = "newshub"
version = "0.1.0"
description = ""
authors = [
    {name = "inal", email = "balkarov05@gmail.com"}
]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = []

[[tool.poetry.packages]]
include = "app"
from = "src"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"